"""What the interface reports as its version.

The stamped module is generated by the build and absent from a source tree, so
it is simulated here rather than written into the package.
"""

import sys
import types

import pytest

from pvechallenge.version import DEV_VERSION, app_version

MODULE = "pvechallenge._version"


@pytest.fixture(autouse=True)
def sans_module_grave(monkeypatch):
    """Start every test from a source tree: nothing stamped."""
    monkeypatch.delitem(sys.modules, MODULE, raising=False)


def graver(version: str, monkeypatch) -> None:
    """Put a stamped module in place, as a build would."""
    module = types.ModuleType(MODULE)
    module.VERSION = version
    monkeypatch.setitem(sys.modules, MODULE, module)


def test_a_source_tree_reports_dev():
    """`pvechallenge/_version.py` is generated: it does not exist here."""
    assert app_version() == DEV_VERSION


def test_a_stamped_version_is_reported(monkeypatch):
    graver("1.2.3", monkeypatch)

    assert app_version() == "1.2.3"


def test_an_empty_stamp_falls_back_to_dev(monkeypatch):
    """A truncated build must not make the window display nothing at all."""
    graver("", monkeypatch)

    assert app_version() == DEV_VERSION
